apiVersion: v1
kind: Service
metadata:
  labels:
    role: redis
    tier: back
  name: redis
  namespace: instavote
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
